[package]
name = "rjvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
bitflags = "1.3"
cesu8 = "1.1"
